LSS-Manager/LSSM-V.4

- docs/en_GB/settings.md
- docs/nl_NL/README.md
- docs/nl_NL/apps.md
- docs/nl_NL/appstore.md
- docs/nl_NL/error_report.md
- docs/nl_NL/faq.md
- docs/nl_NL/metadata.md
- docs/nl_NL/other.md
- docs/nl_NL/settings.md
- docs/nl_NL/suggestions.md
- docs/nl_NL/support.md
First version i made. Maybe it will be updated next time. 
But for now i think everything is ready.
Based on the en_GB version.
> First version of the nl_NL docs + little fix in en_GB

- .all-contributorsrc
- README.md
* @Piet2001 for docs and translations
* @Tsumiki-Chan for infrastructure
> 🔀👥 add contributors

- .travis.yml
- README.md
- build/index.ts
- docs/.vuepress/config.ts
- src/config.ts
> 🔀🔧 dev → master

- docs/it_IT/README.md
This is only needed bc of @KBOE2
> 📝🌐 Fixed a faulty link linking to the FAQ

- docs/cs_CZ/README.md
- docs/cs_CZ/apps.md
- docs/cs_CZ/appstore.md
- docs/cs_CZ/error_report.md
- docs/cs_CZ/settings.md
- docs/en_GB/README.md
> :globe_with_meridians: :memo: Fix translations

- build/index.ts
- scripts/index.ts
> 💚 [build] better building

- src/modules/buildingHover/main.ts
- src/store/api.ts
I hope this will Fix the issue that the status sum is fms_real on the dashboards. 
Could you look if it's affecting an other module?
> 🐛 FMS real/show fix totals under dashboard + Buildinghover fix cellBuildings

- src/modules/enhancedPOI/main.ts
- src/modules/extendedCallWindow/i18n/nl_NL.js
- src/modules/missionHelper/i18n/nl_NL.json
- src/modules/missionHelper/i18n/nl_NL.root.json
- src/modules/missionHelper/missionHelper.vue
- src/modules/missionHelper/settings.ts
- src/store/api.ts
- Update Biketeam only if present
- Fix ehanced POI: window design call API
- Fix FMS_real to FMS_show from States API -> Dashboard
> :bug: 🇳🇱 Update Biketeam, fix ehancedPOI and Fix FMSreal/show

- build/index.ts
- package.json
- src/libraries.json
- src/modules/missionHelper/i18n/fr_FR.json
- webpack.config.ts
- yarn.lock
* I hope, setting transpileOnly does not affect performance on client side.
> 💚 improve build speed a bit

- src/core.ts
Reverts LSS-Manager/LSSM-V.4#282
> Revert ":ambulance: [Telemetry] Possible fix"

- src/modules/extendedCallWindow/assets/arrHover.ts
- src/modules/extendedCallWindow/i18n/cs_CZ.js
- src/modules/extendedCallWindow/i18n/de_DE.js
- src/modules/extendedCallWindow/i18n/en_AU.js
- src/modules/extendedCallWindow/i18n/en_GB.js
- src/modules/extendedCallWindow/i18n/en_US.js
- src/modules/extendedCallWindow/i18n/fr_FR.js
- src/modules/extendedCallWindow/i18n/it_IT.js
- src/modules/extendedCallWindow/i18n/nb_NO.js
- src/modules/extendedCallWindow/i18n/nl_NL.js
Please add German translation by yourself
> 🌐 Add arrHover header translations

- package.json
- src/i18n/en_US.ts
- src/modules/missionHelper/i18n/de_DE.root.json
- src/modules/missionHelper/i18n/en_AU.root.json
- src/modules/missionHelper/i18n/en_GB.root.json
- src/modules/missionHelper/i18n/en_US.root.json
🚑[MissionHelper] Hovertip bug fix
> 🔀🔖 4.1.10-p1

- src/modules/extendedBuilding/assets/expansions.ts
As requested [here](https://canary.discord.com/channels/254167535446917120/632909910895755264/797522807587995658)
> replace colour of building expansion table

- src/modules/extendedCallWindow/i18n/nl_NL.root.json
- src/modules/redesign/i18n/nl_NL/credits/daily.json
- src/modules/redesign/i18n/nl_NL/profile.json
- src/modules/redesign/i18n/nl_NL/vehicle.json
stagingAreaSelectedCounter and redesign
> :globe_with_meridians: nl_NL translations

- src/modules/extendedCallWindow/i18n/en_GB.js
UK: Added "Traffic Car" and "Armed Traffic Car" to "police cars"
> 🐛 ecw UK added missing cars

- src/modules/extendedCallWindow/assets/alarmTime.ts
> 🩹 fixed alarmTime for distance

- src/modules/missionHelper/i18n/nl_NL.json
- src/modules/redesign/components/credits/overview.vue
- src/modules/redesign/components/verband/home.vue
- src/modules/redesign/i18n/de_DE.root.json
- src/modules/redesign/i18n/de_DE/verband.json
- src/modules/redesign/i18n/en_AU.root.json
- src/modules/redesign/i18n/en_GB.root.json
- src/modules/redesign/i18n/en_GB/verband.json
- src/modules/redesign/i18n/en_US.root.json
- src/modules/redesign/i18n/nl_NL.root.json
- src/modules/redesign/i18n/nl_NL/verband.json
- src/modules/redesign/main.ts
- src/modules/redesign/register.json
- src/modules/redesign/settings.ts
- src/modules/statusCounter/i18n/nl_NL.root.js
- src/modules/statusCounter/settings.ts
🚸 [statusCounters] add sort settings on fms_show
🌐 [statusCounters] add nl_NL translations
🐛 [redesign] Fix "/verband/gebauede" link
✨ [redesign] Add settings for routeChecks
✨ [redesign] enable redesign for nl_NL Beta's
🌐 [missionHelper] update nl_NL new prerequisites
🐛 [redesign] verband/home fix apply button disabled
> 🔀[redesign + statusCounters] Enable redesign for nl_NL Beta's, add settings redesign, multiple fixes and nl_NL translations

- src/i18n/en_GB.ts
Added Vehicle Description for every police  unit. Fixed Bugs.
> 🔀🌐 improved 🇬🇧 vehicle translations

- src/modules/extendedCallWindow/i18n/cs_CZ.js
> 🔀🌐🇨🇿 emv: added missing vehicles

- src/modules/dailyCreditsSummary/i18n/nl_NL.root.json
- src/modules/dashboard/components/vehicle-list.vue
- src/modules/redesign/i18n/nl_NL.root.json
- src/modules/redesign/i18n/nl_NL/bewerbungen.json
And translations redesign nl_NL
> 🐛 [dashboard/vehicleList] Fix fms_show after toggleFMS

- src/modules/extendedCallWindow/i18n/de_DE.js
> 🐛[ecw/emv] should work with ELW1 (SEG) now

- src/modules/messageTemplates/docs/fr_FR.md
- src/modules/messageTemplates/i18n/fr_FR.root.json
Includes in-app translations and wiki page.
> [messagesTemplates] Add fr_FR translations

- src/modules/buildingHover/docs/it_IT.md
- src/modules/buildingListFilter/docs/it_IT.md
- src/modules/chatExtras/docs/it_IT.md
- src/modules/chatExtras/i18n/it_IT.root.json
- src/modules/missionHelper/i18n/it_IT.json
> Italian Translation for some modules

- src/modules/redesign/components/credits/daily.vue
Fix for issue between local midnight time and UTC, because the new day will be on page 1, instead max 0.
> 🐛[redesign/dcs] Fix limit button +1

- docs/it_IT/support.md
- src/modules/dailyCreditsSummary/i18n/it_IT.root.json
- src/modules/missionHelper/i18n/it_IT.root.json
The it_IT.ts would be missing but first I have to search for the exact words used for the regex
> Added i18n to dailyCreditsSummary for it_IT and Fix Translations

- src/components/leaflet-map.vue
- src/modules/generalExtensions/assets/mapMarkers.ts
- src/modules/generalExtensions/assets/mapSearches.ts
- src/modules/generalExtensions/main.ts
- src/modules/redesign/components/verband/gebauede.vue
- src/store.ts
- typings/store/RootState.d.ts
This also adds the search feature to the maps added by redesign.
> 🔀✨ [ge/mapSearches] make compatible with LSSM maps

- src/modules/extendedCallList/assets/collapsableMissions/createBtn.ts
- src/modules/extendedCallList/assets/collapsableMissions/missionlist.ts
- src/modules/extendedCallList/assets/collapsableMissions/toggle.ts
- src/modules/extendedCallList/assets/starrableMissions/createBtn.ts
- src/modules/extendedCallList/assets/starrableMissions/mission.ts
- src/modules/extendedCallList/assets/starrableMissions/missionlist.ts
- src/modules/extendedCallList/assets/utils/buttonGroup.ts
- src/modules/extendedCallList/i18n/de_DE.root.json
- src/modules/extendedCallList/i18n/en_AU.root.json
- src/modules/extendedCallList/i18n/en_GB.root.json
- src/modules/extendedCallList/i18n/en_US.root.json
- src/modules/extendedCallList/i18n/nl_NL.root.json
- src/modules/extendedCallList/main.ts
- src/modules/extendedCallList/settings.ts
introduces the new Feature `collapsableMissions` of `extendedCallList` (mentioned in #11)
Also improves the way, buttons are added in front of the alarm-button so that new features are easier to add :)
> 🔀✨ [ecl] collapsableMissions

- src/i18n/en_AU.ts
fix minor incorrect descriptions to units
> [Overview]  🌐🐛 Fix AU Incorrect descriptions

- src/modules/extendedCallWindow/i18n/cs_CZ.root.json
added vehicleCounter and playerCounter for czech version + more translations
> 🔀🌐 [ecl] 🇨🇿 root file

- src/modules/extendedCallWindow/i18n/de_DE.js
Adding staff for FuStW (DGL) in enhancedMissingVehicles
> 🐛 [ecw]  FuStW (DGL) staff

- src/modules/creditsextension/docs/de_DE.md
Hi again 👋 
So, now I have made the documentation for the Toplist-Rank.
Greets
> :memo: Added Toplist-Position

- src/modules/extendedCallWindow/i18n/fr_FR.js
> 🔀🌐🇫🇷 Add missing translation fr_FR 

- src/modules/extendedCallWindow/i18n/fr_FR.js
Example of what's missing. Hoping I'm doing it right.
Thanks!
> [ecw/emv] fr_FR: Add matches for police officers and emergency helicopter

- src/modules/extendedCallWindow/i18n/fr_FR.js
> [ecw/emv] fr_Fr: Add missing regex quantifier for VTU detection.

- src/i18n/en_GB.ts
I also added ranks to rank locked vehicles for both police and fire versions
> [Overview] 🐛✏🌐GB Fixing Outstanding Typos/Missing Words

- README.md
Just a minor URL fix. Otherwise you'll get the cz-Wiki
> 📝[README]add prefix for german wiki

- src/modules/asyncButtons/i18n/sv_SE.json
- src/modules/buildingListFilter/i18n/sv_SE.root.json
- src/modules/creditsextension/i18n/sv_SE.root.json
- src/modules/dailyCreditsSummary/i18n/sv_SE.root.json
- src/modules/dailyCreditsSummary/i18n/sv_SE.ts
- src/modules/dashboard/i18n/sv_SE.json
- src/modules/generalExtensions/i18n/sv_SE.json
- src/modules/generalExtensions/i18n/sv_SE.root.json
- src/modules/heatmap/i18n/sv_SE.json
- src/modules/heatmap/i18n/sv_SE.root.json
- src/modules/support/i18n/sv_SE.root.json
- src/modules/telemetry/i18n/sv_SE.root.json
fix swedish translation async button
> 🔀🌐🇸🇪 update sv_SE translations

- src/modules/buildingListFilter/i18n/fr_FR.root.json
> 🔀🌐🇫🇷 Add Update "Maintien de l'Ordre"

- src/i18n/en_GB.ts
also move the muti role armoured vehicle to arv tab.
> [overview] 🐛🌐 GB Add descriptors to public order units

- src/modules/creditsextension/i18n/cs_CZ.root.json
- src/modules/extendedCallList/i18n/cs_CZ.root.json
Created CZ translation for CreditExtension. Also at extendedCallList added missing functions for CZ file and translated.
> 🔀🌐 [ecl, ce] 🇨🇿 add cs_CZ translations

- docs/it_IT/README.md
- docs/it_IT/apps.md
- docs/it_IT/appstore.md
- docs/it_IT/bugs.md
- docs/it_IT/error_report.md
- docs/it_IT/faq.md
- docs/it_IT/metadata.md
- docs/it_IT/other.md
- docs/it_IT/settings.md
- docs/it_IT/suggestions.md
- docs/it_IT/support.md
I've fixed some grammar mistakes, added the last update regarding being able to export settings, and translated the ones that weren't yet
(I went with this title, not sure if it's correct)
> 🔀🌐🇮🇹 [docs] Update it_IT 

- src/modules/extendedCallWindow/i18n/it_IT.js
- src/modules/redesign/i18n/it_IT/tasks.json
- src/modules/redesign/i18n/it_IT/vehicle.json
(And fixed a small issue with the extended call window)
> 🇮🇹 [redesign] update it_IT translations

- src/modules/extendedCallList/i18n/fr_FR.root.json
```
"currentPrisoners": {
"description": "Shows current amount of patients for each mission",
"title": "Current Prisoners"
},
```
patients or prisoners??
> [ECL] add and fix translate fr_FR

- src/modules/extendedMap/i18n/it_IT.json
- src/modules/extendedMap/i18n/it_IT.root.json
I mess PR names up every time so I've used a placeholder
> 🔀🌐🇮🇹 [em] add it_IT extendedMap translations

- src/i18n/en_GB.ts
dont ask me why we have both "Bridge" and " low bridge"
> 🔀 [Main] 🌐🐛 Add POI "low bridge GB"

- docs/.vuepress/i18n/de_DE.json
- docs/.vuepress/i18n/en_US.json
- docs/.vuepress/i18n/fr_FR.json
- docs/.vuepress/i18n/nl_NL.json
- docs/.vuepress/utils/localeConfig.ts
- docs/fr_FR/contributing/translations.md
You can check for Translating "contributing".
I'm not sure.
> 🔀🌐 [fr_FR] [docs] Update Contributing\Translate and fix translation menu "Contributing"

- src/i18n/nl_NL.ts
- src/i18n/nl_NL/buildings.ts
- src/modules/extendedBuilding/i18n/nl_NL.root.json
- src/modules/extendedCallList/i18n/nl_NL.root.json
- src/modules/extendedCallWindow/i18n/nl_NL.js
- src/modules/extendedCallWindow/i18n/nl_NL.root.json
- src/modules/extendedMap/i18n/nl_NL.json
> 🔀🌐 [nl_NL] add/update translations for eb, ecl, ecw, em and buildinglist

- src/i18n/fr_FR.ts
* fr_FR
* updated translations for core (Update Info Texte)
> 🔀🌐 [fr_FR] Update translations for core

- src/modules/extendedCallWindow/i18n/en_US.js
According to EMS-Chief (https://discord.com/channels/254167535446917120/632909910895755264/981399560612110366 ) does the Foam tanker also counts as Water tanker
en_US
* ...
According to EMS-Chief (https://discord.com/channels/254167535446917120/632909910895755264/981399560612110366 ) does the Foam tanker also counts as Water tanker
> 🇺🇲[ecw] add Foam Tanker to Water tanker

- src/modules/extendedCallWindow/i18n/en_US.js
Als Rescue is a EMS rescue but has transport capabiltys
* en_US
add ALS as ambulance
> [ecw] 🐛🇺🇸 🌐 EN_US add ALS Rescue Ambulance as a Ambulance

- src/modules/buildingListFilter/i18n/fr_FR.root.json
- src/modules/extendedCallList/i18n/fr_FR.root.json
- src/modules/extendedMap/i18n/fr_FR.json
> 🔀🌐 [fr_FR] add/update translations for Em / Ecl / BLF

- src/modules/buildingListFilter/i18n/fr_FR.root.json
- src/modules/extendedMap/i18n/fr_FR.json
> 🔀🌐 [fr_FR] add translations for BLF and EM

- src/modules/chatExtras/i18n/fr_FR.root.json
>   🔀🌐 [fr_FR] Add Translate for Chat Extra

- src/modules/extendedMap/i18n/fr_FR.json
* fr_FR
* new translations for Classrooms
> 🔀🌐 [fr_FR] add/update translations for ExtendedMap 

- src/modules/extendedCallWindow/i18n/en_AU.js
* en_AU
* updated translations for ecw to reflect what is in games
* fixed bug for AU ECW
* ...
Since they updated the names, crew sizes and translations, the ecw has been wrong, in this pull request I have corrected it.
> 🇦🇺🌐🐛 [MH] Fix Updated translations by devs

- src/modules/missionHelper/i18n/en_US.json
* en_US
* singular for lifeguard trucks
> 🌐[mH] fix us singular missing

- src/i18n/fr_FR.ts
- src/i18n/fr_FR/buildings.ts
- src/modules/enhancedTransportRequests/i18n/fr_FR.root.json
- src/modules/extendedMap/i18n/fr_FR.json
- [] a new feature
* fr_FR
* new translations
* Update building "prison" to 20 cells
> 🔀🌐 [fr_FR] add/update translations for core, etr, em and update building

- src/modules/enhancedTransportRequests/docs/fr_FR.md
* fr_FR
* Create docs for enhancedTransportRequests
>  🔀🌐 [fr_FR] Create docs for enhancedTransportRequests

- src/modules/enhancedTransportRequests/i18n/cs_CZ.root.json
- [x ] new translations / updated translations / translation fixes
* cs_CZ
> 🔀🌐 [cs_CZ] add translations for enhancedTransportRequests

- src/modules/extendedCallWindow/i18n/fr_FR.root.json
> 🔀🌐 [fr_FR] add translations for ECW

- src/modules/extendedCallWindow/i18n/pl_PL.root.json
> 🔀🌐 [pl_PL] add translations for extendedCallWindow

- src/modules/creditsextension/i18n/pl_PL.root.json
> 🔀🌐 [pl_PL] update translations for creditsextension

- src/modules/extendedMap/i18n/pl_PL.json
> 🔀🌐 [pl_PL] add translations for extendedMap

- src/i18n/en_GB.ts
- src/i18n/en_US.ts
- src/modules/missionHelper/i18n/en_AU.json
en_US
* new translations for en_US
> 🐛🌐 en_US fix outdated translation main

- src/modules/chatExtras/i18n/pl_PL.root.json
> 🔀🌐 [pl_PL] add translations for chatExtras

- src/modules/hotkeys/i18n/pl_PL.root.json
> 🔀🌐 [pl_PL] add translations for hotkeys

- src/modules/extendedCallWindow/i18n/it_IT.json
* Added Parks Police in extendedCallWindow
>  🔀 [ecw] Add Parks Police it_IT

- src/modules/extendedCallWindow/i18n/cs_CZ.json
- src/modules/hotkeys/i18n/cs_CZ.root.json
> 🔀🌐 [cs_CZ] update translations for extendedCallWindow and hotkeys

- src/modules/extendedCallWindow/i18n/it_IT.json
* Fixed fire fighters aircraft in extendedCallWindow
>  🔀 Fix fire aircrafts in extendedCallWindow, it_IT

- src/modules/extendedCallWindow/i18n/en_GB.json
en_GB
* new translations for ecw
* fixed bug for ECW for the Dog Support Unit
> [ECW] 🐛🌐 Fix DSU Singular Translation

- src/modules/chatExtras/i18n/fi_FI.root.json
- src/modules/hotkeys/i18n/fi_FI.root.json
- src/modules/missionHelper/i18n/fi_FI.json
> 🔀🌐 [mh,hk] add missing fi_FI translations

- src/modules/chatExtras/i18n/fr_FR.root.json
- src/modules/creditsextension/i18n/fr_FR.root.json
- src/modules/generalExtensions/docs/fr_FR.md
- src/modules/heatmap/i18n/fr_FR.json
- src/modules/hotkeys/i18n/fr_FR.root.json
* fr_FR
* new translations for chatExtra
* new translations for creditsextensiom
* new translations for hotkey
* updated translations for generalExtensions/docs
* updated translations for heatmap
> 🔀🌐 [fr_FR] add/update translations

- src/i18n/en_US/buildings.ts
The devs updated the translation for the helicopter station -> Medical helicopter station (still didnt capatilize it though)
* EN_US
* ...
* updated translations for building complex
* fixed bug for bulding complex
* ...
> 🔀 [core] 🇺🇸 🐛🌐 Update HEMS to the new translation by devs

- src/modules/dashboard/i18n/sv_SE.json
* sv_SE
* fix of misspelled field name `modules.dashboard.vehicle-list.target`
>  🔀🌐 [sv_SE]:  Fix misstake translation in dashboard

- src/modules/extendedCallWindow/i18n/en_GB.json
These changes were done by devs -> Photo in LSSM Help Chat
* en_GB
*  updated translations for ecw
* fixed bug for ecw-gb for the arv
* ...
> [ecw] 🇬🇧🐛🌐 Update translations for ARV

- src/i18n/en_GB.ts
It also adds what units count as most noteably the RRV unit
*en_GB
* new translations for overview/main
* updated translations for overview/main
also change PSU -> Public Order
> [Overview/Main] 🇬🇧 🐛🌐Update Vehicle Descripters/Fix Typos

- src/modules/extendedCallWindow/i18n/en_US.json
* en_US
* fixed bug for ecw us allow the small boat trailer to act as boat (cosatal rescue)
* ...
> [ecw] 🇺🇸 🌐🐛 fix small coastal rescue trailer as small boat

- src/modules/chatExtras/i18n/nl_NL.root.json
- src/modules/creditsextension/i18n/nl_NL.root.json
- src/modules/hotkeys/i18n/nl_NL.root.json
* nl_NL
* new translations for chatExtras, creditsextension, hotkeys
> 🔀🌐[ce/hotkeys] add missing nl_NL translations

- docs/en_GB/contributing/translations.md
- docs/en_US/contributing/translations.md
> 📝[docs] fix Typo

- src/modules/redesign/i18n/pl_PL.root.json
* pl_PL
* updated translations for redesign
> 🔀🌐 [pl_PL] update translations for redesign

- src/modules/redesign/components/vehicle.vue
- src/modules/redesign/i18n/de_DE/vehicle.json
- src/modules/redesign/i18n/en_AU/vehicle.json
- src/modules/redesign/i18n/en_GB/vehicle.json
- src/modules/redesign/i18n/en_US/vehicle.json
- src/modules/redesign/i18n/fr_FR/vehicle.json
- src/modules/redesign/i18n/it_IT/vehicle.json
- src/modules/redesign/i18n/nb_NO/vehicle.json
- src/modules/redesign/i18n/nl_NL/vehicle.json
- src/modules/redesign/i18n/pl_PL/vehicle.json
* all
* fix string for patients in redesign vehicles being `{current} of {total}` on all languages:
* add translations for each language
* show a ban icon `🚫` if the mission did not have any patients at all to avoid a `0 of 0` case
> 🔀🚸 [redesign] fix untranslated string

- docs/cs_CZ/other.md
- docs/de_DE/other.md
- docs/en_GB/other.md
- docs/en_US/other.md
- docs/es_ES/other.md
- docs/fr_FR/other.md
- docs/it_IT/other.md
- docs/nb_NO/other.md
- docs/nl_NL/other.md
- docs/pl_PL/other.md
- docs/sv_SE/other.md
* updated the team in docs to the new team structure
> 🔀📝 [docs] update the team

- docs/cs_CZ/README.md
- docs/de_DE/README.md
- docs/en_GB/README.md
- docs/en_US/README.md
- docs/es_ES/README.md
- docs/fi_FI/README.md
- docs/fr_FR/README.md
- docs/it_IT/README.md
- docs/nb_NO/README.md
- docs/nl_NL/README.md
- docs/pl_PL/README.md
- docs/sv_SE/README.md
* added Safari to unsupported browsers on readme for all languages
> 🔀📝 [docs] update browser notes for Safari

- src/modules/hotkeys/i18n/fi_FI.root.json
> 🌐 [hk] Updated fi_FI translation

- .eslintrc.json
- .github/workflows/build.yml
- build/build.sh
- build/index.ts
- scripts/createBuildScript.ts
- src/LSSM-Menu.vue
- src/globals.d.ts
- typings/LSSM-Menu.d.ts
* include the build branch and process it a little by webpack for future purposes
> 🔀✨ [build] let webpack know the build branch

- .github/workflows/build.yml
- scripts/createBuildScript.ts
* Updates of how we push to git (now using an app token which is more secure than using a maschine user)
> 👷‍♂️[build-ci] use app instead of SSH-Keys of user

- docs/cs_CZ/faq.md
- docs/de_DE/faq.md
- docs/en_GB/faq.md
- docs/en_US/faq.md
- docs/es_ES/faq.md
- docs/fr_FR/faq.md
- docs/it_IT/faq.md
- docs/nb_NO/faq.md
- docs/nl_NL/faq.md
- docs/pl_PL/faq.md
- docs/sv_SE/faq.md
* Adds status page in Docs-> FAQ
> 🔀[docs] FAQ=> LSSM status update

- src/modules/missionHelper/i18n/fi_FI.json
> 🌐 [mh] fi_FI bug/typo fix

- src/i18n/en_GB.ts
* en_GB
* fixed bug for POIs to add new poi
* ...
> 🔀🐛🌐 GB [Overview/Enhanced POI] Add new Prison POI

- src/modules/missionHelper/i18n/en_GB.json
* en_GB
* new translations for GB 
* updated translations for MH
* fixed bug for MH
> [MH]🔀🐛🌐🇬🇧 Fix presqusitie typos for specializations

- src/i18n/fi_FI.ts
> 🌐 [core] updated fi_FI translations

- docs/de_DE/settings.md
* 2 Missing Settings for the docs
> 🌐[de_DE] docs update ladekreisel & debug mode

- src/modules/extendedBuilding/i18n/fi_FI.json
- src/modules/extendedBuilding/i18n/fi_FI.root.json
> 🌐 [eb] updated fi_FI translations

- src/i18n/en_AU.ts
* en_AU
* updated translations for overview
* fixed bug for AU - Overview wrong values
> 🔀 [Overview] 🇦🇺🐛🌐 Fix Wrong Values

- src/modules/hotkeys/i18n/fi_FI.root.json
> 🌐 [hk] updated fi_FI translations

- src/modules/asyncButtons/docs/fr_FR.md
- src/modules/buildingHover/docs/fr_FR.md
- src/modules/buildingListFilter/docs/fr_FR.md
- src/modules/buildingListFilter/i18n/fr_FR.root.json
- src/modules/chatExtras/docs/fr_FR.md
- src/modules/chatExtras/i18n/fr_FR.root.json
* fr_FR
* Add Translate Settings for Docs
* Updated translations for BuildingListFilet
* Updated translations for ChatExtra
> 🔀🌐 [fr_FR] update translations for BuildingHover AsyncButtons, ChatExtra and BuildingListFilter 

- docs/nl_NL/metadata.md
- src/i18n/nl_NL.ts
- src/i18n/nl_NL/buildings.ts
- src/modules/extendedBuilding/i18n/nl_NL.json
- src/modules/extendedBuilding/i18n/nl_NL.root.json
- src/modules/extendedCallWindow/i18n/nl_NL.json
- src/modules/hotkeys/i18n/nl_NL.root.json
- src/modules/missionHelper/i18n/nl_NL.json
* nl_NL
* new CP coastguard
* updated translations for eb/hotkeys/branch preview
* fixed personnel amount "hoofdbureau"
> 🔀✨ [Core] 🛥️⛵🌊CP nl_NL

- src/modules/extendedCallWindow/i18n/fi_FI.root.json
> 🔀🌐 [ecw] updated fi_FI translations

- src/modules/extendedCallWindow/i18n/fi_FI.root.json
> 🌐 [acw] updated fi_FI translations

- src/modules/missionHelper/i18n/cs_CZ.root.json
- src/modules/missionHelper/i18n/de_DE.root.json
- src/modules/missionHelper/i18n/en_AU.root.json
- src/modules/missionHelper/i18n/en_GB.root.json
- src/modules/missionHelper/i18n/en_US.root.json
- src/modules/missionHelper/i18n/es_ES.root.json
- src/modules/missionHelper/i18n/fi_FI.root.json
- src/modules/missionHelper/i18n/fr_FR.json
- src/modules/missionHelper/i18n/fr_FR.root.json
- src/modules/missionHelper/i18n/it_IT.root.json
- src/modules/missionHelper/i18n/nb_NO.root.json
- src/modules/missionHelper/i18n/nl_NL.root.json
- src/modules/missionHelper/i18n/pl_PL.root.json
- src/modules/missionHelper/i18n/sv_SE.root.json
- src/modules/missionHelper/missionHelper.vue
* fr_FR
* Hide the title of the vehicles if no vehicle
* [fr_FR]  Update Translation specialization 
* [fr_FR]  Update "height_rescue_personnel" not badge
* Add Title for Special requirements
I'm not sure about the title "Special requirements".
Is it possible to have a preview?
> 🔀Mission Helper Update

- src/modules/extendedMap/i18n/fi_FI.root.json
> 🔀🌐 [em] updated fi_FI translations

- src/i18n/nl_NL/buildings.ts
- src/i18n/nl_NL/global.ts
- src/modules/extendedMap/i18n/nl_NL.root.json
* nl_NL
* new translations for updateUserscript
* new translations for mapCSSFilter
* Add missing extension for Waterreddingspost 
> 🔀🐛🌐 [core/em] missing nl_NL translation and add missing extension

- src/i18n/fr_FR/anniversary.md
* fr_FR
* new translations for Anniversary
> 🔀🌐[fr_FR]Add translations for Anniversary

- docs/fr_FR/faq.md
*fr_FR
* updated translations for DOCS
> 🔀🌐 [fr_FR] update translations for docs

- docs/nl_NL/faq.md
* nl_NL
* updated translations for FAQ docs / Donation Text
> 🔀🌐[docs/faq] nl_NL donations text

- src/modules/extendedCallWindow/i18n/fi_FI.root.json
> 🌐 [ECW] updated fi_FI translations

- src/modules/extendedCallWindow/i18n/de_DE.json
**What kind of update does this PR provide?** 
- [ x] a bugfix for an existing feature / module
* Remove police_motorcycle as police car
* Add police_motorcycle as separate requirement
> 🔀[ECW] add motorcycle to DE

- src/i18n/en_GB.ts
* en_GB
* fixed bug for Enhance poi
> [Enhance POI] 🔀🇬🇧🐛🌐 Add Fire Station POI

- src/modules/hotkeys/i18n/fi_FI.root.json
> 🔀 🌐 [hotkeys] add missing fi_FI translations

- src/modules/extendedCallWindow/i18n/de_DE.json
**What kind of update does this PR provide?** 
* fixed text for rescue_dog_unit
> 🌐 [ecw] fix de_DE Rettungshundestaffel text

- src/i18n/fr_FR.ts
- src/modules/extendedBuilding/i18n/fr_FR.json
- src/modules/extendedBuilding/i18n/fr_FR.root.json
* fr_FR
* updated translations for EB and Core
> 🔀🌐 [fr_FR] add translations for core and EB

- src/modules/missionHelper/missionHelper.vue
- src/modules/missionHelper/settings.ts
* xx_XX
* yy_YY
* ...
* [MH] reverse generated_by and SpecialRequirements
* [MH] removes the title from the key list
can you verify that the "remove title" works
> 🔀[MH] fix the texts and the parameters 

- src/modules/statusCounter/i18n/cs_CZ.root.js
- src/modules/telemetry/i18n/cs_CZ.root.json
> 🔀 🇨🇿 [cs_CZ] add translations for statusCounter and Telemetry

- src/i18n/fi_FI/global.ts
> ✏️🌐 [global] fixed typos fi_FI translations

- src/i18n/fi_FI.ts
> 🐛🌐 [main] fixed bug fi_FI translations

- src/modules/extendedCallWindow/assets/selectedVehicleCounter.ts
* Added color style so the selctedVehicleCounter Table is readable
> 🔀[ecw] Add color Style to SelectedVehicleCounter Table

- src/i18n/en_GB.ts
66, 67, 68, 69, 70, 71, 72 to lifeguard tab.
* en_GB
* updated translations for GB-SAR Pack
> [Main] GB 🌐Update Overview Tabs, Add Unit descriptors.

- src/i18n/es_ES/global.ts
- src/modules/creditsextension/i18n/es_ES.root.json
- src/modules/extendedBuilding/i18n/es_ES.json
- src/modules/extendedBuilding/i18n/es_ES.root.json
- src/modules/extendedCallWindow/i18n/es_ES.root.json
- src/modules/extendedMap/i18n/es_ES.root.json
- src/modules/redesign/i18n/es_ES/vehicle.json
* es_ES
* 
* new translations in different modules and update translations
> Updated translations es_ES

- src/modules/missionHelper/i18n/de_DE.json
- src/modules/missionHelper/i18n/de_DE.root.json
- src/modules/missionHelper/missionHelper.vue
- src/modules/missionHelper/settings.ts
- typings/Mission.d.ts
* de_DE
* yy_YY
* ...
* updated translations for de_DE
* updated the display motorcycles and Civil Patrol
* the settings for mission helper
> 🔀[mh] display motorcycles and Civil Patrol

- src/modules/extendedCallWindow/i18n/en_US.json
* fixed bug for en_us ecw
* ...
> [ECW] 🇺🇸🐛🌐add_foam_trailer to ecw as water tanker

- src/modules/extendedCallWindow/i18n/fi_FI.json
- src/modules/missionHelper/i18n/fi_FI.json
- src/modules/redesign/i18n/fi_FI/verband.json
> ✏️🌐 fixed typos fi_FI translations

- src/modules/extendedCallWindow/i18n/en_US.json
* en_US
* fixed bug for ecw - us to add 67 as a heavy rescye
> 🔀 [ecw]🐛🌐 US Add Lifeguard Rescue as heavy rescue

- src/modules/missionHelper/i18n/fi_FI.json
> 🔀🌐🇫🇮 [mh] added fi_FI translation

- src/modules/dashboard/i18n/fi_FI.json
> 🌐 [db] fixed fi_FI translations

- src/modules/extendedCallWindow/i18n/fi_FI.json
> 🌐 [fi_FI] added translation for ECW

- src/modules/extendedCallWindow/i18n/pl_PL.json
- src/modules/missionHelper/i18n/pl_PL.json
- src/modules/redesign/i18n/pl_PL/alliances.json
- src/modules/redesign/i18n/pl_PL/vehicle.json
> 🔀🌐 [pl_PL] update translations for extendedCallWindow, missionHelper and redesign

- package.json
- yarn.lock
Users have reported huge performance issues on beta which is probably caused by the update of broadcast-channel.
This PR is intended to test on a beta build with 4.x
> 🔀⬇️ downgrade broadcast-channel to 4.x due to performance issues

- src/modules/extendedCallWindow/assets/arrMatchHighlight.ts
- src/modules/extendedCallWindow/i18n/cs_CZ.json
- src/modules/extendedCallWindow/i18n/de_DE.json
- src/modules/extendedCallWindow/i18n/en_AU.json
- src/modules/extendedCallWindow/i18n/en_GB.json
- src/modules/extendedCallWindow/i18n/en_US.json
- src/modules/extendedCallWindow/i18n/es_ES.json
- src/modules/extendedCallWindow/i18n/fi_FI.json
- src/modules/extendedCallWindow/i18n/fr_FR.json
- src/modules/extendedCallWindow/i18n/it_IT.json
- src/modules/extendedCallWindow/i18n/nb_NO.json
- src/modules/extendedCallWindow/i18n/nl_NL.json
- src/modules/extendedCallWindow/i18n/pl_PL.json
- src/modules/extendedCallWindow/main.ts
* arrHighlight should work even on fire alarm system missions or expanded missions
> ✨ [emv] arrHighlight add ignore phrases

- src/modules/extendedCallWindow/i18n/en_AU.json
* en_AU
* yy_YY
* ...
* Added vehicles for the bushfire missions
> 🔀 🇦🇺 [emv] add BushfireVehicles

- src/modules/extendedCallWindow/assets/vehicleListPermanentSearch.ts
- src/modules/extendedCallWindow/i18n/cs_CZ.root.json
- src/modules/extendedCallWindow/i18n/de_DE.root.json
- src/modules/extendedCallWindow/i18n/en_AU.root.json
- src/modules/extendedCallWindow/i18n/en_GB.root.json
- src/modules/extendedCallWindow/i18n/en_US.root.json
- src/modules/extendedCallWindow/i18n/es_ES.root.json
- src/modules/extendedCallWindow/i18n/fi_FI.root.json
- src/modules/extendedCallWindow/i18n/fr_FR.root.json
- src/modules/extendedCallWindow/i18n/it_IT.root.json
- src/modules/extendedCallWindow/i18n/nb_NO.root.json
- src/modules/extendedCallWindow/i18n/nl_NL.root.json
- src/modules/extendedCallWindow/i18n/pl_PL.root.json
- src/modules/extendedCallWindow/i18n/sv_SE.root.json
- src/modules/extendedCallWindow/main.ts
- src/modules/extendedCallWindow/settings.ts
* Enables the vehicle search bar permantly
* Closes #2308
> 🔀[ecw] add permanent search bar

- src/i18n/de_DE/vehicles.ts
- src/modules/extendedCallWindow/i18n/de_DE.json
* ECW: NEA200 can be used if NEA50 is requested
* LKW Lbw can have two possible trainings
> 🔀[ecw/eb] Correction NEA200

- src/modules/extendedBuilding/assets/expansions.ts
* all
* Feature request implementation from #2430 
> 🎉[eb] Feature request implementation

- docs/fr_FR/faq.md
- src/modules/clock/i18n/fr_FR.root.json
- src/modules/extendedCallList/i18n/fr_FR.root.json
- src/modules/extendedCallWindow/i18n/fr_FR.root.json
- src/modules/extendedMap/i18n/fr_FR.json
- src/modules/hotkeys/i18n/fr_FR.root.json
- src/modules/missionHelper/i18n/fr_FR.root.json
* fr_FR
* new translations for Clock
* new translations for Hotkey
* new translations for ECL
* update translations for FAQ
* update translations for ECW
* update translations for MH
> 🔀🌐 [fr_FR] update many translations

- src/modules/extendedCallWindow/i18n/en_US.json
* xx_XX
* yy_YY
* ...
* ...
added K9 Carrier (large and small) to patrol car
> 🔀 [emv] en_US add K9 Carrier (large and small) to patrol car

- src/modules/extendedCallWindow/i18n/nl_NL.json
> Fix SB not counting as SL

- src/modules/extendedCallWindow/i18n/it_IT.json
Just fixed riot police in it_IT
> 🔀[it_IT] Fix Riot police

- src/modules/enhancedTransportRequests/docs/nl_NL.md
* nl_NL
* new translation for enhancedTransportRequests
Proper edit. Apologies for wrong pull request.
>  🔀🌐 [nl_NL] add/update translations for enhancedTransportRequests

- src/modules/missionHelper/i18n/sv_SE.json
- src/modules/missionHelper/i18n/sv_SE.root.json
Added vehicle caption
* sv_SE
* new SE translation for mission helper
> [sv_SE] add/update translations for missionHelper

- src/modules/missionHelper/i18n/fr_FR.json
- src/modules/missionHelper/i18n/fr_FR.root.json
> 🔀🌐 [fr_FR] add translations for MissionHelper

- docs/en_US/settings.md
* en_US
* updated settings.md which was outdated
> 🔀🌐 [en_US] updated settings.md which was outdated

- docs/en_GB/settings.md
* en_GB
* updated settings.md which was outdated
> 🔀🌐 [en_GB] updated settings.md which was outdated

- src/modules/asyncButtons/i18n/en_AU.json
- src/modules/asyncButtons/i18n/en_GB.json
- src/modules/asyncButtons/i18n/en_US.json
- src/modules/asyncButtons/i18n/es_ES.json
- src/modules/asyncButtons/i18n/it_IT.json
- src/modules/asyncButtons/i18n/sv_SE.json
Fixed misspell
* en_AU
* fixed typo
>  🔀🌐 [en_AU] fixed typo

- src/i18n/cs_CZ/buildings.ts
- src/i18n/en_AU/buildings.ts
- src/i18n/en_GB/buildings.ts
- src/i18n/en_US/buildings.ts
- src/i18n/nl_NL/buildings.ts
- src/modules/extendedCallWindow/i18n/en_GB.json
- src/modules/extendedCallWindow/i18n/en_US.json
to most actives countries
* some countries
* Large guard adds
> ✨[core] Large guard adds

- src/modules/missionHelper/i18n/sv_SE.root.json
Updated pump_water_amount text.
* sv_SE
* Added pump_water_amount translation in missionHelper for sv_SE
> [sv_SE] add translations for missionHelper (pump_water_amount)

- .github/workflows/build.yml
- build/build.sh
> 🔀 👽️ change due to a browserslist change

- src/i18n/en_GB/buildings.ts
- src/i18n/en_GB/vehicles.ts
fix credit price
add drone to CRS
* en_GB
* fix credit price
add drone to CRS
> 🐛[GB] Fix Coast Guard

- .gitignore
- docs/en_GB/contributing/development.md
- docs/en_US/contributing/development.md
- package.json
- prebuild/downloadMissions.ts
- prebuild/index.ts
- src/generated/libraries.json
- yarn.lock
* en_US
* download of `https://v4.lss-manager.de/missions/de_DE.json` during prebuild phase
* developer documentation on how to setup a local environment
- source: https://discord.com/channels/254167535446917120/254174068947943425/1201286038186897468
> 🔀🔨 Dev-setup documentation, prebuild mission download

- src/stores/api.ts
* internal API to fetch vehicles or buildings based on a dispatch center
Required for upcoming feature, but not necessarily related.
> 🔀✨ get vehicles and buildings by dispatch center

- .github/workflows/extendedCallList-mapping.yml
* comparison was hardcoded to `de_DE`
* locales without any mapping so far yielded errors (`sv_SE`)
* locales where all events have been mapped were still shown in the issue
> 🔀🐛 fix github action for extendedCallList

- .github/workflows/extendedCallList-mapping.yml
* fix unnecessary github issue closing when the issue is already closed
* fix filtering when issue has been closed
* update issue text when all events have been mapped
- see workflow/action error https://github.com/LSS-Manager/LSSM-V.4/actions/runs/7863781945/job/21454794402#step:10:10
- closed issue preview: https://github.com/buffcode/LSSM-V.4/issues/4
> 🔀🔨 improve eCL github issue handling

- docs/en_GB/deployment
- docs/en_US/deployment/api.md
* Small chapter how to deploy the api on own webserver
>  🔀[docs] add api deploy instructions

- src/i18n/fr_FR.ts
- src/modules/buildingListFilter/i18n/fr_FR.root.json
* xx_XX
* yy_YY
* ...
* Fix Vehicles for dashboard FR
* Fix Buildinglist
* ...
> 🔀🌐 [fr_FR] Fix Vehicles for dashboard

- src/modules/missionHelper/i18n/fr_FR.json
> 🔀🌐 [fr_FR] Fix véhicles captions translations for MissionHelper

- docs/en_US/contributing/development.md
- package.json
* update docs for local deployment
* Add new command https://github.com/LSS-Manager/LSSM-V.4/blob/2cca3667961a23d44dc6f7808de206f1b48f33c9/package.json#L8 to run the local build without running shell commands
> 📝[docs] fix local deploy documentation

- src/i18n/cs_CZ.ts
- src/i18n/cs_CZ/buildings.ts
- src/i18n/cs_CZ/global.ts
- src/i18n/cs_CZ/schoolings.ts
- src/i18n/cs_CZ/vehicles.ts
* cs_CZ
* fix src/i18n/cs_CZ.ts to real data from operacni-stredisko.cz + cs_CZ translation
* fix vehicles in src/i18n/cs_CZ/vehicles.ts to real data from operacni-stredisko.cz + cs_CZ translation
* fix buildings in src/i18n/cs_CZ/buildings.ts to real data from operacni-stredisko.cz + cs_CZ translation
* add schoolings to src/i18n/cs_CZ/schoolings.ts
* updated translations for src/i18n/cs_CZ/global.ts
> 🔀🌐 [cs_CZ] add/update translations for vehicle, buildings, etc.

- src/modules/extendedCallWindow/i18n/de_DE.json
-Count staff count railway rescue and police helicopter with hoist
-Add railway rescue as regular LF+RW
-Add police helicopter with hoist as regular police helicopter
-Add small hose equipment as SW
> 🔀🐛 [ECW][DE]: Fix railway rescue and police helicopter with hoist

- CONTRIBUTING.md
Fix incorrect address.
* xx_XX
* yy_YY
* ...
* ...
> [✏️] Fix typo in CONTRIBUTING.md
